### ISSUE TITLE
Provide shift left/shift right functionality

### ISSUE THREAD

**Issue by delfuego** [de-jcup/eclipse-yaml-editor#102]
It'd be nice if this editor provided shift left/shift right functionality, like most of the Eclipse code editors (e.g., https://help.eclipse.org/2021-03/index.jsp?topic=%2Forg.eclipse.cdt.doc.user%2Ftasks%2Fcdt_t_shift_code.htm&resultof%3D%2522%2573%2568%2569%2566%2574%2522%2520%2522%2572%2569%2567%2568%2574%2522%2520).

Is there any way this might be possible?

**Comment by de-jcup** [comment]
There is mentioned:

>     In the C/C++ editor, select the full length of the lines that you want to shift.
>     Do one of the following:
>         To move the text to the right, press Tab.
>         To move the text to the right, click Edit > Shift Right.
>         To move the text to the left, press Shift+Tab.
>         To move the text to the left, click Edit > Shift Left.
> 

At the moment you can do
- Format the document (context menu "Source" -> "Format"
- After this is done, select a wanted text area to move with mouse
  * Pressing `Tab` will move right
  * Pressing `Shift` + `Tab` will move left
- The move left , move right does use always same length of spaces

So, the functionality is basically available.

Looking at Java IDE, I found it inside `Source` menu (and not in `Edit`)
![image](https://user-images.githubusercontent.com/11644753/117627540-8fb30c80-b178-11eb-991f-0bfe56e3f730.png)

So do you only miss dedicated actions "Move left", "Move right" in the source menu (and context menu) ?

**Comment by delfuego** [comment]
@de-jcup I literally had no idea that Eclipse hid the shift-right/shift-left functionality behind the tab/shift-tab keyboard shortcuts! So I *was* missing the functionality entirely, but now I'm just missing the source and context menu items.
So I'm good now using the tab/shift-tab keys (if I remember!), but it'd certainly be nice to also see the menu items.

**Comment by de-jcup** [comment]
Just select the wanted area and open context menu (right mouse click). Inside the menu you will find `Shift right` and `Shift left `as well.

![image](https://user-images.githubusercontent.com/11644753/124829374-d3f43a80-df78-11eb-8e44-548ac8a953a1.png)

so i will close this issue
