### ISSUE TITLE
Update vulnerable snakeyaml dependency

### ISSUE THREAD

**Issue by apozzo** [de-jcup/eclipse-yaml-editor#104]
According to oss index snakeyaml version 1.24 is vulnerable
see https://ossindex.sonatype.org/component/pkg:maven/org.yaml/snakeyaml@1.24

this dependency should be updated to at least to version 1.26
see https://ossindex.sonatype.org/component/pkg:maven/org.yaml/snakeyaml@1.26

all available versions from maven central repository search
https://search.maven.org/artifact/org.yaml/snakeyaml

thanks a lot for all your eclipse editor plugins, it helps me a lot.

**Comment by de-jcup** [comment]
Thanx for reporting, will upgrade to snakeyaml 1.29 - see https://mvnrepository.com/artifact/org.yaml/snakeyaml/1.29

**Comment by de-jcup** [comment]
I just released 1.7.1 on eclipse marketplace with this fix.
