### ISSUE TITLE
Add some function to copy compound (qualified, full path) key to clipboard

### ISSUE THREAD

**Issue by foal** [de-jcup/eclipse-yaml-editor#105]
Sometimes it is necessary to have a full path of a simple key (e.g. `product.feature.eco_code.enabled`). Now I need to pass over the overview and copy key-by-key for each level. Will be nice if the plugin will provide such functionality - "copy qualified key".

**Comment by de-jcup** [comment]
Hmm, as far as understood you want for 

``` yaml
product:
  feature: 
    eco_code: 
      enabled: true
```

 to click in the outline to element and have inside context menu the option "copy qualified key" and this shall copy 
`product.feature.eco_code.enabled` to clipboard?

**Comment by foal** [comment]
Yes, exactly.

**Comment by de-jcup** [comment]
![image](https://user-images.githubusercontent.com/11644753/124828637-d609c980-df77-11eb-893f-fdbc55168bb3.png)

![image](https://user-images.githubusercontent.com/11644753/124828960-431d5f00-df78-11eb-8ffc-7514015b943d.png)
