### ISSUE TITLE
Allow formatter to keep blank lines

### ISSUE THREAD

**Issue by toellrich** [de-jcup/eclipse-yaml-editor#110]
The formatter currently always removes blank lines. It would be great if, just like with the XML editor (see attached screenshot), it would be configurable to keep blank lines.

![Preferences_2022_03_17_10_25_17](https://user-images.githubusercontent.com/5838959/158779687-2f454a96-6d6e-4680-9889-6dba39415cf0.png)
.

**Comment by de-jcup** [comment]
The formatting/pretty printing is done by `snake yaml parser`.

AFAIKS when looking at
https://bitbucket.org/snakeyaml/snakeyaml/wiki/Documentation `snake` does not provide an option to keep blank lines.

So it would be necessary to create a workaround here - like done for comments (which are always dropped by `snake)`.

**Comment by de-jcup** [comment]
## New preference entry
With last commit you have a new preference entry (per default the "Clear all blank lines" is disabled like in IntelliJ)
![image](https://user-images.githubusercontent.com/11644753/162128644-63530612-efcf-4470-bdba-961a9cc42e3a.png)

## An example
### Origin
![image](https://user-images.githubusercontent.com/11644753/162128826-9aa928da-7b02-4a62-9d82-34fb04bbadd5.png)
### Formatted with "Clear blank lines" enabled

### Formatted with "Clear blank lines" enabled

**Comment by de-jcup** [comment]
@toellrich : Just release 1.9.0 on eclipse marketplace - so feature is available now.
