### ISSUE TITLE
Please support the eclipse dark theme.

### ISSUE THREAD

**Issue by Ravisankar-Challa** [de-jcup/eclipse-yaml-editor#23]
This plugin is really cool. But doesn't look good in dark theme

![image](https://user-images.githubusercontent.com/11788842/41466308-0c0ae550-70e5-11e8-9e27-5bb8a6d7409b.png)

**Comment by de-jcup** [comment]
Hello @Ravisankar-Challa , dark theme is supported, but you have (currently) to activate dark theme colors manually in preference (same as described for bash editor at https://github.com/de-jcup/eclipse-bash-editor/wiki/FAQ#how-to-apply-default-dark-theme-colours but look for preferences of yaml editor...)

Hope this helps.

**Comment by de-jcup** [comment]
With V1.0.0 I will adpt the solution done for asciidoctor editor in https://github.com/de-jcup/eclipse-asciidoctor-editor/pull/63 to provide an automated theme support without the workaround with "Restore defaults for dark theme" button in preferences.

**Comment by Ravisankar-Challa** [comment]
Thanks a lot for the tip.

**Comment by de-jcup** [comment]
You are wellcome :-)

**Comment by de-jcup** [comment]
I fixed the white panel too.

With version 1.0.0 the editor will now (when using dark theme defaults from preferences page) look like:

![image](https://user-images.githubusercontent.com/11644753/41909161-9e1a57d2-7946-11e8-934e-b133b5a520b9.png)

**Comment by Ravisankar-Challa** [comment]
:+1: 
I feel gray color for text is not so appealing. 
![image](https://user-images.githubusercontent.com/11788842/41967313-ab4c80d4-7a44-11e8-9d9f-f6fe7c7401e0.png)

**Comment by de-jcup** [comment]
Hello @Ravisankar-Challa. I think that coloring is always very subjective and everyone's a matter of taste. Everybody has the option to change the colors by editors preference dialog. So I think I will leave the colors as is - maybe in future there are some changes. 

If you like you can create another issue for dark theme colors. When many users do like the **same** changes at coloring for dark theme defaults I would change them.
