### ISSUE TITLE
Not an issue just a request - Please improve the default dark theme colors

### ISSUE THREAD

**Issue by Ravisankar-Challa** [de-jcup/eclipse-yaml-editor#29]
In eclipse xml editor & java editor gray color is used for commented code.

**Comment by de-jcup** [comment]
Hello @Ravisankar-Challa , so you would prefer using 

'java_single_line_comment=128,128,128' from
https://github.com/eclipse/eclipse.jdt.ui/blob/master/org.eclipse.jdt.ui/css/e4-dark_jdt_syntaxhighlighting.css

for yaml comments.

I think reusing same colors as on Java-Editor site is a very good way to get most interests of people. Nice!
I will integrate it as wished.

**Comment by de-jcup** [comment]
Maybe it would be a good choice to use some of the other colors from java setup for dark theme too.

            'colorNormalText=192,192,192' -> java_default=217,232,247 for normal text 
		'colorYamlKeywords=85,255,255' -> 'java_doc_keyword=154,140,124'
		'colorBooleans=88,98,98' >  'semanticHighlighting.number.color=104,151,187'
		'colorDoubleStrings=128,128,0' > 'java_string=23,198,163'
		'colorSingleStrings=0,128,128'  > 'java_string=23,198,163'
		'colorComments=128,128,128', >'java_single_line_comment=128,128,128'
		'colorMappings=86,156,214' > 'java_keyword=204,108,29'
		'colorBlock=49,98,98' > keep
		'colorHyperlink=49,98,98' > 'java_doc_link=169,156,140'

I tried out those settings and it looks very fine for myself:

![image](https://user-images.githubusercontent.com/11644753/42002717-8a5d120c-7a68-11e8-97d0-18b8d3f7588e.png)

What do you think?

**Comment by de-jcup** [comment]
Current dark theme variant (with the grey already changed as wished) looks not so good:

![image](https://user-images.githubusercontent.com/11644753/42003149-47cce92e-7a6a-11e8-8293-cd1b36509f70.png)
