### ISSUE TITLE
[feature request] Block commenting

### ISSUE THREAD

**Issue by paulvi** [de-jcup/eclipse-yaml-editor#30]
It would be nice to be able to comment block (several selecting lines with `#` symbol)  or current line
by pressing `<Ctrl>+</>` (what is default in Eclipse for comenting block)

**Comment by de-jcup** [comment]
This is alrady implemented:

CTRL+ 7 = ...

![image](https://user-images.githubusercontent.com/11644753/42319821-6eab2da0-8053-11e8-801e-c79f5a57395c.png)

**Comment by paulvi** [comment]
indeed Ctrl+7 works
