### ISSUE TITLE
Incorrect apostrophe colour highlighting

### ISSUE THREAD

**Issue by PyvesB** [de-jcup/eclipse-yaml-editor#32]
Hello @de-jcup,

I believe I've spotted an issue with the highlighting. Consider a simple YAML key-value string pair containing an apostrophe:
`some-key: there's an apostrophe in this string!`

The editor gets the colours wrong and seems to think that a new string starts at the apostrophe:
![yaml](https://user-images.githubusercontent.com/10694593/47182987-d2910880-d31e-11e8-90d0-1304077127ab.PNG)

Thanks,

Pyves

**Comment by de-jcup** [comment]
Hi @PyvesB , looks like an bug. will be fixed...

Thanks for reporting.

**Comment by de-jcup** [comment]
Some links to documentation

- http://yaml.org/spec/1.2/spec.html#id2802842
- http://blogs.perl.org/users/tinita/2018/03/strings-in-yaml---to-quote-or-not-to-quote.html

It seems `YamlStringRule` has to be improved much.

**Comment by de-jcup** [comment]
Hm... escaping is also wrong.
You must escape with '' not \'
see http://yaml.org/spec/current.html#id2534365
