### ISSUE TITLE
Folding actions: expand all /collapse all

### ISSUE THREAD

**Issue by de-jcup** [de-jcup/eclipse-yaml-editor#34]
It's sometimes a little bit cumbersome to use folding feature : you have to select all parts wanted to be folded per mouse click.

When there are big documents and user wants a fast overview it maybe more convenient to have 
context menu entries inside editor about 

"Expand all folding"
"Collopse all foldings"

Maybe also an preference entry (disabled per default) "enable auto collapse foldings on editor startup"
should be introduced as well. The quick outline and the outline are showing always complete content,
so still accessible.

@PyvesB what do you think about this idea ?

**Comment by PyvesB** [comment]
It's a good idea in my opinion, especially with the ability to tune the default behaviour in the preferences. There's also a nice feature in some Eclipse editors, "Toggle folding", which completely hides/unhides the folding buttons from the entire editor. 😉

**Comment by de-jcup** [comment]
Ruler context menu has got now the actions:
![image](https://user-images.githubusercontent.com/11644753/48590918-bf834f80-e941-11e8-9792-b53695f6b55c.png)

When folding is disabled, then expand/collapse all are disabled as well:
![image](https://user-images.githubusercontent.com/11644753/48591022-30c30280-e942-11e8-9150-4bb7e161a34d.png)

Preferences now in ruler context menu pointing to yaml editor preferences. Also changed text and behaviour so the global setup is now only for new opened editors:
![image](https://user-images.githubusercontent.com/11644753/48591116-a62ed300-e942-11e8-82c8-bb82fd03ee87.png)

**Comment by PyvesB** [comment]
Nice, adding it to the ruler context menu seems like good user experience. 👍

**Comment by de-jcup** [comment]
Thanks. I am using multiple devices for development. And the commit was on a machine completely reinstalled...

**Comment by de-jcup** [comment]
did forced push, and changed author...
