### ISSUE TITLE
(feature request) Make "tab width" spaces configurable

### ISSUE THREAD

**Issue by arboriginal** [de-jcup/eclipse-yaml-editor#36]
Hi,

I'm using Eclipse since a few days, and your Yaml Editor (version 1.0) is in it.

I saw in #9 you voluntary fix tab replacement to 3 spaces. It could be a good idea to let users be able to configure this as 2 or 4 is often used (never seen 3 spaces before).

I don't know how the implementation is done in Eclipse but you could maybe re-use the value in:
General > Editors> Text-editor => Displayed tab width (or implement a settings in Yaml editor section).

**Comment by de-jcup** [comment]
Hello @arboriginal, good idea. Will add extra preference entry with 3 as default.
Will come with Version 1.1.0

**Comment by de-jcup** [comment]
In upcoming version 1.1.0 this can be configured now as shown in next picture.
(default is still 3, min=1, max=20)

![image](https://user-images.githubusercontent.com/11644753/49327502-16547000-f563-11e8-97eb-c6ea43386346.png)

**Comment by de-jcup** [comment]
Just release 1.1.0 on marketplace which contains feature...
