### ISSUE TITLE
Handle Tab + SHIFT tab on text selections

### ISSUE THREAD

**Issue by de-jcup** [de-jcup/eclipse-yaml-editor#42]
When pressing `TAB` inside editor it will be replaced by configured amount of spaces (done in preferences).

So far so good... but...

When doing a selection of text and pressing either `TAB`or `SHIFT`+ `TAB` the editor content selection
is just crushed.

The behaviour should be as following in` ReplaceTabBySpacesVerifyKeyListener`:

When `TAB` is pressed
- check if multiline selection when not do as normal
- when multiline get content, split lines, add n-amount of spaces to each line start and insert

`SHIFT TAB` is currently not implemented at all but should work complete opposite way:
- remove n-amount of ANY CHAR before line x

**Comment by de-jcup** [comment]
As this seems to be a very generic approach it could - when working - added to   [eclipse-commons](https://github.com/de-jcup/eclipse-commons) project and just used here.

**Comment by f18m** [comment]
Hi @de-jcup ,
sorry to bother you but I have again a few problems launching the plugin from my Eclipse.
My problem is that I followed
  https://www.youtube.com/watch?v=9_AQouAvehY&feature=youtu.be
(with the obvious difference that I imported from an already-cloned GIT repo of my fork of this plugin) 
but I get a project in my eclipse that builds
   src/main/java
but not
  src/main/java-eclipse

(as instead in my BashEditor plugin workspace!)... the result is of course that when I create a launch configuration and run it I get: "Plug-in de.jcup.yamleditor was unable to load class de.jcup.yamleditor.YamlEditor."
See this screenshot:  
  https://imgur.com/a/9W2AscB

I tried already to run by terminal both
  ./gradlew build
  ./gradlew eclipse
as written here https://github.com/de-jcup/eclipse-bash-editor/wiki/Contribution
Maybe I can't remember how I managed to get BashEditor plugin or maybe there's something different with this YAML plugin... 

Thanks

**Comment by f18m** [comment]
Btw I noticed that: 
 if I import from git the yaml plugin sources in a Eclipse that does NOT contain the EGradle Editor plugin, then I get the 
  eclipse-yaml-editor/yamleditor-plugin/src/main/java-eclipse 
folder recognized and built BUT the compiler will complain about the missing required build path "yamleditor-other".

If I install the EGradle plugin to get the "yamleditor-other" folder recognized and present, I loose the "java-eclipse" folder....

I must be missing something :)
Sorry I'm mostly a C++ developer... all this Java stuff is a bit confusing to me :)

**Comment by de-jcup** [comment]
Hello @f18m 

yaml editor has no dependency to egradle plugin runtime. Neither das Egradle itself change anything. I will explain the java parts :

A eclipse java project does always rely on the` .classpath` file inside the project. There are the external dependencies listed but also all source folders used for compilation. When you initally clone the repository and look (at least) into master you will something like:
![image](https://user-images.githubusercontent.com/11644753/52919932-ce461d80-3307-11e9-90cb-e5da5b84f23b.png)

The selection shows the source pathes. So the "normal" java stuff and also the eclipse dedicated parts are contained out of the box.

I tried out at my console a `./gradlew cleanEclipse eclipse` and did after that a `git status`. Classpathes did not change at all!

> If I install the EGradle plugin to get the "yamleditor-other" folder recognized and present, I loose the "java-eclipse" folder....

Ahem - EGradle is one of my plugins and I am using it to get things working in eclipse-it works good enough for my whishes. But you don't even need egradle to get things working. When you want the "yamleditor-other" project be available (it does only contain special test parts and some other non-eclipse stuff and is most time not needed) you just need to call gradle wrapper.

In next comment I will excercise a complete new import to an temporary, empty workspace.

**Comment by de-jcup** [comment]
![image](https://user-images.githubusercontent.com/11644753/52920162-f898da80-3309-11e9-9710-dd0f7d25aea2.png)
Then in eclipse:
![image](https://user-images.githubusercontent.com/11644753/52920184-2c740000-330a-11e9-818d-fc4b14428e56.png)
After Next:
![image](https://user-images.githubusercontent.com/11644753/52920199-51687300-330a-11e9-9f2e-17b2ee98e8dd.png)
Then 4 projects are imported. No errors. Now create a "Eclipse Application Launch configuration":
![image](https://user-images.githubusercontent.com/11644753/52920221-82e13e80-330a-11e9-8193-82f82fea4627.png)
When pressing Run I get 
![image](https://user-images.githubusercontent.com/11644753/52920238-aad0a200-330a-11e9-90ef-96ed23826b61.png)
And then pressing continue the Runtime eclipse started, I created a temp project and a `test.yaml `file inside. All is working.

So normally easiest way is to
- clone repo
- call  gradle wrapper with cleanEclipse eclipse
- import the projects as "existing projects".

**Comment by de-jcup** [comment]
**About your import problems:**
Hm... the only thing I could think about is that you accidently used not EGradle but Buildship-Plugin and this did some setup for Gradle execution (EGradle does only call command line and does no magic at all, so console world and Eclipse world are always same. Buildship uses the API of gradle and does some magic stuff on project classpathes (e.g adding gradle dependencies as a special library folder inside project).

I hope it works now. If not, don't hesitate to contact me again.

**Comment by f18m** [comment]
Hi @de-jcup ,
my problem was the missing step "./gradlew cleanEclipse eclipse" BETWEEN the git import and the eclipse import. I was doing that step AFTER the eclipse import and then trying to import the "eclipse-others" project ... that was a bit painful.
By doing the gradle step before the import in Eclipse it worked just fine, thanks!!!

**Comment by de-jcup** [comment]
@f18m : Good work thank you :+1:  Works very well

I have merged it into master now. I will start to adopt the solution as an API for eclipse-commons see https://github.com/de-jcup/eclipse-commons/issues/12 . When this is done , I will reintegrate API variant to yaml editor and bash editor.

**Comment by de-jcup** [comment]
@f18m I just release yaml-editor V1.3.0 on eclipse marketplace. Your changes are online :-) 

Best wishes 
Albert

**Comment by f18m** [comment]
Thanks @de-jcup , I took a look at the refactoring, very good work!!
