### ISSUE TITLE
Syntax highlighting problem

### ISSUE THREAD

**Issue by de-jcup** [de-jcup/eclipse-yaml-editor#52]
Originally requested at:
https://marketplace.eclipse.org/comment/5435#comment-5435

> When my text is aaa:bb, aaa:bb should be a string and their colors are the same.But now aaa: is blue and bb is black

**Comment by de-jcup** [comment]
Hmm.. in version 1.4.0 using dark theme it looks correct:
![image](https://user-images.githubusercontent.com/11644753/54982432-21685b80-4fab-11e9-8c0d-d8ab4564c462.png)

**Comment by de-jcup** [comment]
At windows with white theme: (1.3.0 and 1.4.0
![image](https://user-images.githubusercontent.com/11644753/54982919-13670a80-4fac-11e9-9a94-87ed70a06591.png)

So I am currently not able to underststand the problem.

**Comment by JiangJungle** [comment]
aws is a list with 4 element.The first element is a black string aa.The second element is a string bb:bb and its color should be black.But now,bb: is not black.The third element and the fourth element is a map that has one element.The color of key should be blue,but d.key is black.

![TIM截图20190328115915](https://user-images.githubusercontent.com/48972772/55133413-9630c680-5160-11e9-8bfb-7c01421515a5.png)

**Comment by de-jcup** [comment]
I will fix the syntax highlighting in the near future.

**Comment by de-jcup** [comment]
After bugfix, the example looks now like:

![image](https://user-images.githubusercontent.com/11644753/55720437-1e388b00-5a01-11e9-8c95-4c89feaf7777.png)
