### ISSUE TITLE
Formatter doesn't allow indentation of 2 spaces

### ISSUE THREAD

**Issue by way2sukh** [de-jcup/eclipse-yaml-editor#54]
![Screenshot_1](https://user-images.githubusercontent.com/20796818/55060025-7df47500-5096-11e9-9661-fb6902e898f6.png)

**Comment by de-jcup** [comment]
Hello @way2sukh , 
I tried out if snake yaml parser accepts 2 indent - yes it does. Only 1 is not accepted. I thought it was not accepting 2.

Will make a hotfix release.

**Comment by de-jcup** [comment]
I just released 1.4.1 on marketplace where the behaviour is changed an you can use 2 in preferences.

Best wishes
Albert

**Comment by way2sukh** [comment]
Thank you, it works.
