### ISSUE TITLE
A way to sort element items

### ISSUE THREAD

**Issue by cvgaviao** [de-jcup/eclipse-yaml-editor#56]
I'm using this editor to edit some OpenAPI based yaml file.
Those file contains a schemas: section that can contain many items and it can become very extensive.
Would be awesome the editor to provide a way to sort selected elements. Also would be nice to see outline view in a sorted way.

**Comment by de-jcup** [comment]
Hm. Sorting elements in outline view should be no great issue.

Changing the yaml source inside could be a little bit tricky. Should be possible as well, but do you really want to have your content changed ?

If you don't mind you could append a example for such files - so I would have something to test...

**Comment by cvgaviao** [comment]
Yep, when your file became big have it sorted it is a great thing. 
Today I just copied one file and converted it to json, sorted it and them converted it back to yaml...

This is a good example: https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v3.0/petstore-expanded.yaml

**Comment by de-jcup** [comment]
Okay. How would you like to have your content sorted?

For example:

```
x:
  c: 1
  b: 2
a:
  d: 3
  a: 4
```
a sort could lead to
variant 1:
```
a:
  d: 3
  a: 4 
x:
  c: 1
  b: 2
```
or variant 2:
```

a:
  a: 4 
  d: 3
x:
  b: 2
  c: 1
```
So its about deep sort and only sorting first...

**Comment by cvgaviao** [comment]
Hi,
to me, the best would be to sort the first level children, something like your variant 1, but just for a selected node in the tree.

**Comment by de-jcup** [comment]
Sorting of single yaml block does work. But sorting of only selected tree item makes problems - I do not know if this will work. I will try out a little bit more, but when it still makes problems, sorting will be only implemented for complete editor file.

**Comment by de-jcup** [comment]
Sorting implemented for complete document(s). Available from source menu (main menu or by context menu inside editor)

![image](https://user-images.githubusercontent.com/11644753/68093704-afd58180-fe98-11e9-9177-5d210e99f807.png)

The action will change the source code and sort all mappings in ascending way:

![image](https://user-images.githubusercontent.com/11644753/68093718-e6130100-fe98-11e9-892e-05f58c561562.png)

After action is done the outline view will also show up the new ordering.

**Comment by de-jcup** [comment]
If there are comments inside the files these are removed at the moment. To make user aware of this situation in this case there comes up a confirmation dialog:

![image](https://user-images.githubusercontent.com/11644753/68093837-3179df00-fe9a-11e9-8625-0e24571893bc.png)

**Comment by de-jcup** [comment]
### Additional information: 
https://github.com/de-jcup/eclipse-yaml-editor/issues/76 supports go templates - but sorting will not be supported for those sanitized files. Reason: Its still not valid yaml - sanitizing is okay to get an outline. But sorting is not possible, because origin content shall not change...

Currently nothing is done when sanitizing was necessary to get a working yaml for outline. It will fail silently, not visible for user. If the yaml file is still valid for such file (this can happen in some cases) sorting is possible there.
