### ISSUE TITLE
Bug: setting Indent value to something else than 3 doesn't work

### ISSUE THREAD

**Issue by mxmlnglt** [de-jcup/eclipse-yaml-editor#63]
Setting 2 as the Indent value.
Creating a brand new file, hit the Tab key: I get 3 spaces, not 2

I even tried to RESTART Eclipse, but still doesn't work.

Windows 10 Pro (64-bit)
Eclipse IDE for Enterprise Java Developers.
Version: 2019-03 (4.11.0)
Build id: 20190314-1200

I installed the plugin through the Eclipse Marketplace so it's Yaml Editor 1.4.2

**Comment by de-jcup** [comment]
Hello,

did you really setup the "spaces used for tab replacement" as shown in next picture
![image](https://user-images.githubusercontent.com/11644753/57973625-2e526b80-79ac-11e9-83c0-d9efbfafbda7.png)

or did you setup the formatter (see next picture)
![image](https://user-images.githubusercontent.com/11644753/57973648-69ed3580-79ac-11e9-8a4f-2bc3ff1ca0d4.png)

I tried out Yaml Editor 1.4.2 and with settings "spaces used for tab replacement"  it replaces amount tabs as defined.

The second setup on "formatter" preference is used only for the source formatter (`CTRL`+`SHIFT`+`F`)

**Comment by mxmlnglt** [comment]
OK, that was the 2nd one, I though it was applied by typing, not just by calling Ctrl+Shift+F.

But I find it odd, because there isn't supposed to have tabs in yaml source (per specification). So why not merge these two settings in one? When typing a tab => indent by the number of chars.

Also the option "Source formatter max line length" should be in the formatter screen, given the "formatter" word.

Finally, saw a typo: Code Assistence => Code Assistance

**Comment by arboriginal** [comment]
Hi,

I confirm mxmIngit is right:
When using Ctrl+Shift+F, it consider 3 spaces whatever you choose.

**Comment by de-jcup** [comment]
Okay, this seems to lead always to a misunderstanding. So I will merge the property as suggested:

- Only "Formatter" sub page will contain setup for amount of spaces then
  YamlEditorPreferenceConstants.P_SPACES_TO_REPLACE_TAB will be removed
  YamlEditorPreferenceConstants.P_SOURCE_FORMAT_INDENT will be used instead
- YamlEditorPreferenceConstants.P_SOURCE_FORMAT_LINE_LENGTH will be removed
  from root page (is currently existing on root and on "Formatter" sub page
- Typo (if still exists) will be fixed
