### ISSUE TITLE
Update site

### ISSUE THREAD

**Issue by AsharLohmar** [de-jcup/eclipse-yaml-editor#65]
Hi 
I wanted to give this plugin a try, but, as I'm not a fan of the marketplace, I was looking for an "update site" but can't seem to find one anywhere. So, is there one ?
Thanks

**Comment by de-jcup** [comment]
The update site is at https://dl.bintray.com/de-jcup/yamleditor
Currently the plugin is not signed. So you will see a message about this on installation

Just an additional remark: Using the eclipse marketplace has some benefits: 
- You can setup your favorites and automatically install them on every new eclipse instance
- You have an update mechanism (I am not sure if update mechanism is for direct installed plugins too)
- Your download ranks the plugin up  ;-) 
- Its more stable and faster than in earlier releases
