### ISSUE TITLE
Editor shows non-existent characters

### ISSUE THREAD

**Issue by asfernandes** [de-jcup/eclipse-yaml-editor#66]
This happens for me with some frequency from previous version to the latest (1.4.2) one.

I do not have a reproducible test case.

The editor shows non existent characters in the end of line (most times in the last line).

On this image, I just typed the "end" key and the caret go to the real end of file. The duplicated semicolon does not exist. But if I delete it with "delete" key, it really deletes the single semicolon and when I open the file again there will be no semicolon.

![yaml-editor](https://user-images.githubusercontent.com/529415/60668896-6837de00-9e43-11e9-898b-1fecbc9aff0d.png)

**Comment by asfernandes** [comment]
There is also times that no character is showed, but it exists in the file.

The problems always happens in the last character of a line.

**Comment by de-jcup** [comment]
Sorry, I am not able to reproduce it.

But I had some sort of this in other editors - not only my own. 

Please do me a favor: If you have such behaviour again, please open the eclipse error log view 
![image](https://user-images.githubusercontent.com/11644753/68748235-5ab61000-05fc-11ea-8720-011ef149edb9.png)

and look if there has been something added as error or warning in this time period.

Having an example file where this happens often would be also very helpful

**Comment by de-jcup** [comment]
Long time no changes here - close issue
