### ISSUE TITLE
Sequence of mappings not displayed correctly in outline view

### ISSUE THREAD

**Issue by alexirion** [de-jcup/eclipse-yaml-editor#72]
The following sequence of mappings is not correctly displayed in the outline view:

```
List:
- Name: A
  Year: 1970
- Name: B
  Year: 1971
```

Under "List" there should be two nodes (A and B), each with the sub-nodes for name and year.
However, the four nodes for name and year are flattened under the List node, as shown in this screenshot:

![yamlEditor](https://user-images.githubusercontent.com/55915075/66706320-4fd43b00-ed31-11e9-930d-21f99c760e0a.png)

**Comment by de-jcup** [comment]
![image](https://user-images.githubusercontent.com/11644753/66831855-ea629300-ef58-11e9-8d2b-fbe202421bc2.png)

**Comment by de-jcup** [comment]
@alexirion : Thanx for reporting. Will come with release 1.6.0
