### ISSUE TITLE
Missing requirement org.apache.ws.jaxme when installing from update site

### ISSUE THREAD

**Issue by LorenzoBettini** [de-jcup/eclipse-yaml-editor#78]
I'm not using the MarketPlace and install the YAML editor from the update site https://dl.bintray.com/de-jcup/yamleditor

I seem to understand that version 1.6.0 has an additional requirement osgi.bundle,org.apache.ws.jaxme,0.5.1.v20100427-1100 which is not part of the official Eclipse release update site (I guess it was in the past), so the installation fails unless one explicitly adds the additional Orbit update site (e.g., http://download.eclipse.org/tools/orbit/downloads/2019-09) which contains the above bundle.

It might be worthwhile to document that?

**Comment by de-jcup** [comment]
Hello @LorenzoBettini ,

I have not explicit added a dependency to `org.apache.ws.jaxme`
Inside my plugin manifest it looks like:
![image](https://user-images.githubusercontent.com/11644753/68746548-1d03b800-05f9-11ea-9865-15932cb5d04c.png)
(or see code at https://github.com/de-jcup/eclipse-yaml-editor/blob/master/yamleditor-plugin/META-INF/MANIFEST.MF )

So my plugin should not be repsonsible for this dependency.

I guess you did not only update yaml editor but maybe some other parts? Making an update with other plugins will bring up a dependency problem even when not responsible for... I have seen this before.

**Comment by LorenzoBettini** [comment]
That's quite strange since yaml-editor is the only one I was trying to update, but of course you're right about yaml-editor not depending on the jaxme bundle. On a second thought this might be due to my switch to Java 11 before updating.
Sorry for the noise :)
