### ISSUE TITLE
How to associate with .yaml files

### ISSUE THREAD

**Issue by stpruitt** [de-jcup/eclipse-yaml-editor#89]
What is the trick to get the editor associated with .yaml files?  The File Associations -> Editor Selection list does not show the editor.

I installed the plugin and restarted Eclipse.

**Comment by j-ulrich** [comment]
It should simply work if you go to Preferences -> General -> Editors -> File Associations and then:

1. If *.yaml or *.yml is not in the list of file types, add it with the "Add..." button and then select it in the "File types:" list
2. Click "Add..." next to "Associated editors:"
3. Select "Internal Editors"
4. Select "Yaml Editor"

![Bildschirmfoto 2020-05-08 um 21 38 51](https://user-images.githubusercontent.com/1260380/81442825-94fc0680-9174-11ea-83fb-59a6d2d1fc55.png)

**Comment by stpruitt** [comment]
That's exactly what I did and Yaml Editor doesn't show up.  In fact, nothing shows up.

Thanks.

________________________________

**Comment by de-jcup** [comment]
@stpruitt : Hmm..this is strange. Another user had mentioned a similar problem with another jcup plugin (bash editor) - but it was not reproducable.
Please restart your eclipse and check inside error view if there are any entries related to yaml editor. If you find something, please add it to this issue.

You could try to uninstall the yaml plugin and do a new install by eclipse marketplace.

**Comment by aaiezza** [comment]
I've uninstalled and reinstalled thrice now. Still no YAML editor showing up in my list.
I'm using Eclipse 2020-06.

**Comment by de-jcup** [comment]
Hello @aaiezza , I just tried out with a fresh Eclipse Java IDE 2020-06 and recorded as video https://youtu.be/AJw4WKSqQdc  - I have no such issues. Have you tried out a fresh eclipse 2020-06 package from https://eclipse.org/downloads like shown in next screen and try to install the editor?

![image](https://user-images.githubusercontent.com/11644753/86179172-15623680-bb2a-11ea-9ec7-5350d0624960.png)

There was a similar issue at https://github.com/de-jcup/eclipse-yaml-editor/issues/60 and there is a description how to get more information (error logs etc.) - if you have more information please add to this issue.

**Comment by aaiezza** [comment]
@de-jcup The video is great! Thank you for that.

But sadly, I’m not sure what could be wrong.

This plugin worked like a charm in Eclipse 2019-12. Then I installed 2020-06 fresh and opened up my existing workspace. Everything worked, except this plugin.
Then I tried another fresh install of Eclipse 2020-06 and a fresh workspace. Still nothing.
It is just missing from the internal editors list.

You also shot this video on a Windows machine.
Could this have anything to do with me being on macOS?

**Comment by aaiezza** [comment]
@de-jcup the plugin works perfectly for me on fresh eclipse installations on Ubuntu and Windows 10.

I’m assuming it could be a macOS thing…

**Comment by de-jcup** [comment]
Unfortunately I have currently no access to a Mac, but normally it should not be an OS specific problem. The only OS specific components are SWT - all other stuff in eclipse is normally platform independent. 

Have you tried a fresh eclipse installation on your mac as well?

**Comment by agmckee** [comment]
I just experienced this on Eclipse 2020-03 on Linux (Debian). It is odd, it works fine on my Ubuntu laptop but not on my Debian desktop.

Eclipse IDE for Java Developers
Version: 2020-03 (4.15.0)
Build id: 20200313-1211
OS: Linux, v.4.19.0-10-amd64, x86_64 / gtk 3.24.5
Java version: 11.0.8

**Comment by de-jcup** [comment]
@vogella - Those problems were mentioned in some of my plugins, was not able to find an issue at eclipse bugtracking. Do you know a bug inside the platform?

**Comment by de-jcup** [comment]
Long time no changes here - so closing this issue
