### ISSUE TITLE
User mentioned problems rendering yaml files at eclipse marketplace

### ISSUE THREAD

**Issue by de-jcup** [de-jcup/eclipse-yaml-editor#96]
At https://marketplace.eclipse.org/comment/7166#comment-7166 a user mentioned problems with rendering yaml files inside editor plugin.
So tried out with Asciidoctor Editor Version 2.2.0

Example contains embedded way (version 1) and also included variant (version 2):
![image](https://user-images.githubusercontent.com/11644753/94994888-d0232a00-059a-11eb-90b7-dd67546985e1.png)

But it works out-of-the-box without any problems.

**Comment by de-jcup** [comment]
Was not able to reproduce, so closing issue.

**Comment by smt-mj** [comment]
this is my current attempt. yes it includes my file, but in comparison to mvn rendering, it doesnt work. see attached screenshot.
![yml-import-test](https://user-images.githubusercontent.com/72379544/95065320-2d38f000-0701-11eb-860e-97c8877a183d.png)
