### ISSUE TITLE
toggle comment eats 2nd char after #

### ISSUE THREAD

**Issue by elonderin** [de-jcup/eclipse-yaml-editor#97]
the problem is that it assumes a space after the `#`.

example where each `->` is a toggle:

` #foo -> oo -> # oo`

this seems to be independent of selected line endings but i'm on windows but have only \n

**Comment by de-jcup** [comment]
Yes this is a bug,

`#foo -> oo -> # oo` was always changed to `# oo -> oo -> # oo`

**Comment by de-jcup** [comment]
![image](https://user-images.githubusercontent.com/11644753/124832347-d6f12a00-df7c-11eb-8cce-bc8febb6e66b.png)

 pressing `CTRL + 7` we got:

![image](https://user-images.githubusercontent.com/11644753/124832386-e6707300-df7c-11eb-840a-5247c8853b3e.png)

and pressing `CTRL + 7` again 

![image](https://user-images.githubusercontent.com/11644753/124832431-f6885280-df7c-11eb-9446-6a1c7d5a5d27.png)
